eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: eureka-service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: first-caller-consumer
    api-b:
      path: /api-b/**
      serviceId: eureka-service-feign